name: Trigger auto deployment for mycontainerapp25032025

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/mycontainerapp25032025-AutoDeployTrigger-129e78d7-c043-4433-950b-54776e19ca93.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.MYCONTAINERAPP25032025_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.MYCONTAINERAPP25032025_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.MYCONTAINERAPP25032025_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: 
          registryUsername: ${{ secrets.MYCONTAINERAPP25032025_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.MYCONTAINERAPP25032025_REGISTRY_PASSWORD }}
          containerAppName: mycontainerapp25032025
          resourceGroup: anandatheerthan
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


